[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    tzapu/WiFiManager
    knolleary/PubSubClient
    bblanchon/ArduinoJson
    adafruit/RTClib
    adafruit/Adafruit MAX31865 library
    olikraus/U8g2

build_flags =
    -DCORE_DEBUG_LEVEL=3